/* C++ code produced by gperf version 3.0.3 */
/* Computed positions: -k'1,3,13,$' */

#if !(                                                                         \
    (' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) && ('%' == 37) && \
    ('&' == 38) && ('\'' == 39) && ('(' == 40) && (')' == 41) &&               \
    ('*' == 42) && ('+' == 43) && (',' == 44) && ('-' == 45) && ('.' == 46) && \
    ('/' == 47) && ('0' == 48) && ('1' == 49) && ('2' == 50) && ('3' == 51) && \
    ('4' == 52) && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) && \
    ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) && ('=' == 61) && \
    ('>' == 62) && ('?' == 63) && ('A' == 65) && ('B' == 66) && ('C' == 67) && \
    ('D' == 68) && ('E' == 69) && ('F' == 70) && ('G' == 71) && ('H' == 72) && \
    ('I' == 73) && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) && \
    ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) && ('R' == 82) && \
    ('S' == 83) && ('T' == 84) && ('U' == 85) && ('V' == 86) && ('W' == 87) && \
    ('X' == 88) && ('Y' == 89) && ('Z' == 90) && ('[' == 91) &&                \
    ('\\' == 92) && (']' == 93) && ('^' == 94) && ('_' == 95) &&               \
    ('a' == 97) && ('b' == 98) && ('c' == 99) && ('d' == 100) &&               \
    ('e' == 101) && ('f' == 102) && ('g' == 103) && ('h' == 104) &&            \
    ('i' == 105) && ('j' == 106) && ('k' == 107) && ('l' == 108) &&            \
    ('m' == 109) && ('n' == 110) && ('o' == 111) && ('p' == 112) &&            \
    ('q' == 113) && ('r' == 114) && ('s' == 115) && ('t' == 116) &&            \
    ('u' == 117) && ('v' == 118) && ('w' == 119) && ('x' == 120) &&            \
    ('y' == 121) && ('z' == 122) && ('{' == 123) && ('|' == 124) &&            \
    ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error \
    "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

//
// DO NOT MODIFY THIS FILE! AUTO GENERATED BY clay/tools/make_keywords.py
//

#include "clay/ui/component/keywords.h"

#include <string>

namespace clay {
struct TokenValue {
  short name;
  short id;
};

#define TOTAL_KEYWORDS 237
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 35
#define MIN_HASH_VALUE 38
#define MAX_HASH_VALUE 634
/* maximum key range = 597, duplicates = 0 */

class KeywordHash {
 private:
  static inline unsigned int hash(const char *str, unsigned int len);

 public:
  static const struct TokenValue *find(const char *str, unsigned int len);
};

inline unsigned int KeywordHash::hash(const char *str, unsigned int len) {
  static const unsigned short asso_values[] = {
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      113, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 7,   635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 178, 59,  98,  214, 9,   254, 21,  202,
      36,  6,   6,   69,  10,  76,  135, 19,  635, 8,   16,  6,   91,  33,  201,
      105, 101, 7,   635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635, 635,
      635};
  unsigned int hval = len;

  switch (hval) {
    default:
      hval += asso_values[(unsigned char)str[12]];
    /*FALLTHROUGH*/
    case 12:
    case 11:
    case 10:
    case 9:
    case 8:
    case 7:
    case 6:
    case 5:
    case 4:
    case 3:
      hval += asso_values[(unsigned char)str[2]];
    /*FALLTHROUGH*/
    case 2:
    case 1:
      hval += asso_values[(unsigned char)str[0]];
      break;
  }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

struct StringPool_t {
  char StringPool_str38[sizeof("type")];
  char StringPool_str39[sizeof("repeat")];
  char StringPool_str41[sizeof("scroll-left")];
  char StringPool_str43[sizeof("mask-repeat")];
  char StringPool_str44[sizeof("mask-size")];
  char StringPool_str45[sizeof("mask-image")];
  char StringPool_str47[sizeof("perspective")];
  char StringPool_str51[sizeof("tag")];
  char StringPool_str53[sizeof("scroll-top")];
  char StringPool_str54[sizeof("mask-clip")];
  char StringPool_str55[sizeof("scroll-enable")];
  char StringPool_str60[sizeof("scroll-forward-mode")];
  char StringPool_str61[sizeof("idSelector")];
  char StringPool_str62[sizeof("scroll-bar-track-color")];
  char StringPool_str65[sizeof("visible")];
  char StringPool_str67[sizeof("exposure-ui-margin-left")];
  char StringPool_str68[sizeof("exposure-ui-margin-right")];
  char StringPool_str69[sizeof("itemkeys")];
  char StringPool_str70[sizeof("exposure-screen-margin-left")];
  char StringPool_str71[sizeof("exposure-screen-margin-right")];
  char StringPool_str73[sizeof("exposure-ui-margin-bottom")];
  char StringPool_str76[sizeof("exposure-screen-margin-bottom")];
  char StringPool_str77[sizeof("sticky-offset")];
  char StringPool_str79[sizeof("exposure-ui-margin-top")];
  char StringPool_str81[sizeof("border")];
  char StringPool_str82[sizeof("exposure-screen-margin-top")];
  char StringPool_str83[sizeof("bottom-inset")];
  char StringPool_str84[sizeof("border-left")];
  char StringPool_str85[sizeof("border-right")];
  char StringPool_str87[sizeof("border-color")];
  char StringPool_str88[sizeof("border-style")];
  char StringPool_str90[sizeof("edit-on-focus")];
  char StringPool_str96[sizeof("border-top")];
  char StringPool_str97[sizeof("select")];
  char StringPool_str98[sizeof("border-top-style")];
  char StringPool_str99[sizeof("name")];
  char StringPool_str100[sizeof("border-bottom")];
  char StringPool_str102[sizeof("min-height")];
  char StringPool_str103[sizeof("list-type")];
  char StringPool_str104[sizeof("border-bottom-color")];
  char StringPool_str105[sizeof("border-bottom-style")];
  char StringPool_str109[sizeof("border-left-style")];
  char StringPool_str110[sizeof("markdown-style")];
  char StringPool_str111[sizeof("prev-scrollable")];
  char StringPool_str112[sizeof("border-radius")];
  char StringPool_str113[sizeof("mask-origin")];
  char StringPool_str114[sizeof("border-top-left-radius")];
  char StringPool_str116[sizeof("value")];
  char StringPool_str118[sizeof("border-bottom-left-radius")];
  char StringPool_str119[sizeof("border-bottom-right-radius")];
  char StringPool_str120[sizeof("cursor")];
  char StringPool_str121[sizeof("text")];
  char StringPool_str122[sizeof("scroll-direction")];
  char StringPool_str123[sizeof("richtype")];
  char StringPool_str124[sizeof("scroll-orientation")];
  char StringPool_str125[sizeof("caret-color")];
  char StringPool_str126[sizeof("scroll-bar-enable")];
  char StringPool_str127[sizeof("exposure-scene")];
  char StringPool_str128[sizeof("text-indent")];
  char StringPool_str129[sizeof("needs-visible-cells")];
  char StringPool_str131[sizeof("max-height")];
  char StringPool_str132[sizeof("text-maxline")];
  char StringPool_str133[sizeof("scroll-y")];
  char StringPool_str136[sizeof("text-gradient")];
  char StringPool_str137[sizeof("scroll-x")];
  char StringPool_str139[sizeof("maxlines")];
  char StringPool_str140[sizeof("ignore-focus")];
  char StringPool_str142[sizeof("border-top-right-radius")];
  char StringPool_str143[sizeof("cap-insets")];
  char StringPool_str144[sizeof("scroll-bar-auto-hide")];
  char StringPool_str146[sizeof("vertical-orientation")];
  char StringPool_str150[sizeof("skip-redirection")];
  char StringPool_str151[sizeof("scroll-without-focus")];
  char StringPool_str152[sizeof("vertical-align")];
  char StringPool_str154[sizeof("item-key")];
  char StringPool_str155[sizeof("z-index")];
  char StringPool_str157[sizeof("outline")];
  char StringPool_str158[sizeof("list-main-axis-gap")];
  char StringPool_str159[sizeof("sticky")];
  char StringPool_str160[sizeof("visibility")];
  char StringPool_str162[sizeof("line-height")];
  char StringPool_str163[sizeof("prevent-loading-on-list-scroll")];
  char StringPool_str165[sizeof("bounce")];
  char StringPool_str167[sizeof("scroll-event-throttle")];
  char StringPool_str168[sizeof("initial-scroll-offset")];
  char StringPool_str170[sizeof("outline-color")];
  char StringPool_str172[sizeof("outline-style")];
  char StringPool_str173[sizeof("bounces")];
  char StringPool_str176[sizeof("level")];
  char StringPool_str177[sizeof("blur-radius")];
  char StringPool_str178[sizeof("line-spacing")];
  char StringPool_str180[sizeof("color")];
  char StringPool_str183[sizeof("experimental-recycle-sticky-item")];
  char StringPool_str185[sizeof("column-count")];
  char StringPool_str186[sizeof("letter-spacing")];
  char StringPool_str187[sizeof("content")];
  char StringPool_str189[sizeof("background-repeat")];
  char StringPool_str190[sizeof("border-left-color")];
  char StringPool_str191[sizeof("mask-position")];
  char StringPool_str192[sizeof("background-image")];
  char StringPool_str193[sizeof("intersection-observers")];
  char StringPool_str194[sizeof("send-composing-input")];
  char StringPool_str195[sizeof("confirm-type")];
  char StringPool_str197[sizeof("text-align")];
  char StringPool_str198[sizeof("controls")];
  char StringPool_str202[sizeof("auto-size")];
  char StringPool_str203[sizeof("transform")];
  char StringPool_str204[sizeof("adjust-mode")];
  char StringPool_str206[sizeof("border-right-color")];
  char StringPool_str207[sizeof("border-right-style")];
  char StringPool_str208[sizeof("consume-slide-event")];
  char StringPool_str209[sizeof("show-soft-input-onfocus")];
  char StringPool_str211[sizeof("next-focus-left")];
  char StringPool_str215[sizeof("src")];
  char StringPool_str216[sizeof("placeholder")];
  char StringPool_str217[sizeof("background-size")];
  char StringPool_str220[sizeof("loop-count")];
  char StringPool_str225[sizeof("word-break")];
  char StringPool_str226[sizeof("border-top-color")];
  char StringPool_str227[sizeof("loop")];
  char StringPool_str228[sizeof("list-cross-axis-gap")];
  char StringPool_str231[sizeof("scroll-backward-mode")];
  char StringPool_str232[sizeof("next-focus-up")];
  char StringPool_str233[sizeof("dataset")];
  char StringPool_str234[sizeof("text-stroke-color")];
  char StringPool_str235[sizeof("hit-slop")];
  char StringPool_str237[sizeof("mode")];
  char StringPool_str238[sizeof("text-decoration")];
  char StringPool_str239[sizeof("next-focus-right")];
  char StringPool_str240[sizeof("cap-insets-scale")];
  char StringPool_str241[sizeof("align-focus")];
  char StringPool_str242[sizeof("scroll-bar-auto-hide-delay")];
  char StringPool_str243[sizeof("enable-font-scaling")];
  char StringPool_str244[sizeof("speed")];
  char StringPool_str247[sizeof("image-config")];
  char StringPool_str248[sizeof("list-container-info")];
  char StringPool_str249[sizeof("preload")];
  char StringPool_str250[sizeof("scroll-to-id")];
  char StringPool_str251[sizeof("image-transition-style")];
  char StringPool_str253[sizeof("exposure-id")];
  char StringPool_str255[sizeof("overflow-y")];
  char StringPool_str256[sizeof("scroll-bar-thumb-color")];
  char StringPool_str257[sizeof("white-space")];
  char StringPool_str258[sizeof("background-origin")];
  char StringPool_str259[sizeof("overflow-x")];
  char StringPool_str260[sizeof("background-clip")];
  char StringPool_str262[sizeof("scroll-bar-thumb-hover-color")];
  char StringPool_str263[sizeof("scroll-bar-thumb-active-color")];
  char StringPool_str264[sizeof("next-scrollable")];
  char StringPool_str265[sizeof("scroll-bar-thumb-radius")];
  char StringPool_str266[sizeof("initial-scroll-index")];
  char StringPool_str268[sizeof("allow-escape")];
  char StringPool_str270[sizeof("transition")];
  char StringPool_str275[sizeof("smart-scroll")];
  char StringPool_str276[sizeof("experimental-batch-render-strategy")];
  char StringPool_str277[sizeof("upper-threshold-item-count")];
  char StringPool_str278[sizeof("scroll-bar-width")];
  char StringPool_str280[sizeof("enable-scrollbar")];
  char StringPool_str281[sizeof("border-width")];
  char StringPool_str285[sizeof("uiappear")];
  char StringPool_str286[sizeof("image-rendering")];
  char StringPool_str287[sizeof("text-single-line-vertical-align")];
  char StringPool_str290[sizeof("enable-new-animator")];
  char StringPool_str293[sizeof("autoplay")];
  char StringPool_str295[sizeof("readonly")];
  char StringPool_str297[sizeof("auto-fix")];
  char StringPool_str298[sizeof("border-bottom-width")];
  char StringPool_str299[sizeof("animation")];
  char StringPool_str307[sizeof("direction")];
  char StringPool_str312[sizeof("transform-origin")];
  char StringPool_str316[sizeof("background-color")];
  char StringPool_str320[sizeof("placeholder-color")];
  char StringPool_str321[sizeof("border-top-width")];
  char StringPool_str323[sizeof("text-shadow")];
  char StringPool_str324[sizeof("uidisappear")];
  char StringPool_str326[sizeof("maxlength")];
  char StringPool_str331[sizeof("block-native-event")];
  char StringPool_str333[sizeof("text-maxlength")];
  char StringPool_str336[sizeof("text-selection")];
  char StringPool_str337[sizeof("filter")];
  char StringPool_str338[sizeof("enable-scroll")];
  char StringPool_str339[sizeof("animation-style")];
  char StringPool_str344[sizeof("user-interaction-enabled")];
  char StringPool_str345[sizeof("clip-path")];
  char StringPool_str347[sizeof("font-weight")];
  char StringPool_str348[sizeof("font-size")];
  char StringPool_str349[sizeof("font-style")];
  char StringPool_str353[sizeof("overflow")];
  char StringPool_str355[sizeof("need-visible-item-info")];
  char StringPool_str358[sizeof("scroll-to-index")];
  char StringPool_str361[sizeof("preferred-focus-child")];
  char StringPool_str365[sizeof("-x-auto-font-size")];
  char StringPool_str370[sizeof("focusable")];
  char StringPool_str373[sizeof("focus")];
  char StringPool_str375[sizeof("box-shadow")];
  char StringPool_str379[sizeof("enable-exposure-ui-margin")];
  char StringPool_str381[sizeof("background")];
  char StringPool_str382[sizeof("low-quality")];
  char StringPool_str384[sizeof("next-focus-fallback")];
  char StringPool_str385[sizeof("-x-auto-font-size-preset-sizes")];
  char StringPool_str387[sizeof("background-position")];
  char StringPool_str390[sizeof("use-soft-keyboard")];
  char StringPool_str391[sizeof("-x-app-region")];
  char StringPool_str397[sizeof("exposure-area")];
  char StringPool_str400[sizeof("border-right-width")];
  char StringPool_str402[sizeof("animation-velocity")];
  char StringPool_str403[sizeof("update-animation")];
  char StringPool_str404[sizeof("accessibility-element")];
  char StringPool_str407[sizeof("next-focus-down")];
  char StringPool_str410[sizeof("full-screen")];
  char StringPool_str415[sizeof("accessibility-elements")];
  char StringPool_str421[sizeof("opacity")];
  char StringPool_str430[sizeof("experimental-update-sticky-for-diff")];
  char StringPool_str434[sizeof("auto-save-last-child")];
  char StringPool_str435[sizeof("event-through")];
  char StringPool_str437[sizeof("lower-threshold-item-count")];
  char StringPool_str442[sizeof("font-family")];
  char StringPool_str448[sizeof("downsampling")];
  char StringPool_str450[sizeof("scroll-bar-thumb-width")];
  char StringPool_str452[sizeof("disabled")];
  char StringPool_str455[sizeof("scroll-bar-thumb-min-length")];
  char StringPool_str465[sizeof("accessibility-label")];
  char StringPool_str468[sizeof("focus-index")];
  char StringPool_str474[sizeof("upper-threshold")];
  char StringPool_str480[sizeof("placeholder-font-weight")];
  char StringPool_str481[sizeof("placeholder-font-size")];
  char StringPool_str482[sizeof("fullscreen-mode")];
  char StringPool_str487[sizeof("border-left-width")];
  char StringPool_str490[sizeof("enable-nested-scroll")];
  char StringPool_str492[sizeof("update-list-info")];
  char StringPool_str526[sizeof("text-overflow")];
  char StringPool_str531[sizeof("text-stroke-width")];
  char StringPool_str553[sizeof("focus-smooth-scroll")];
  char StringPool_str558[sizeof("outline-width")];
  char StringPool_str561[sizeof("drop-shadow")];
  char StringPool_str599[sizeof("defer-src-invalidation")];
  char StringPool_str634[sizeof("lower-threshold")];
};
static const struct StringPool_t StringPool_contents = {
    "type",
    "repeat",
    "scroll-left",
    "mask-repeat",
    "mask-size",
    "mask-image",
    "perspective",
    "tag",
    "scroll-top",
    "mask-clip",
    "scroll-enable",
    "scroll-forward-mode",
    "idSelector",
    "scroll-bar-track-color",
    "visible",
    "exposure-ui-margin-left",
    "exposure-ui-margin-right",
    "itemkeys",
    "exposure-screen-margin-left",
    "exposure-screen-margin-right",
    "exposure-ui-margin-bottom",
    "exposure-screen-margin-bottom",
    "sticky-offset",
    "exposure-ui-margin-top",
    "border",
    "exposure-screen-margin-top",
    "bottom-inset",
    "border-left",
    "border-right",
    "border-color",
    "border-style",
    "edit-on-focus",
    "border-top",
    "select",
    "border-top-style",
    "name",
    "border-bottom",
    "min-height",
    "list-type",
    "border-bottom-color",
    "border-bottom-style",
    "border-left-style",
    "markdown-style",
    "prev-scrollable",
    "border-radius",
    "mask-origin",
    "border-top-left-radius",
    "value",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "cursor",
    "text",
    "scroll-direction",
    "richtype",
    "scroll-orientation",
    "caret-color",
    "scroll-bar-enable",
    "exposure-scene",
    "text-indent",
    "needs-visible-cells",
    "max-height",
    "text-maxline",
    "scroll-y",
    "text-gradient",
    "scroll-x",
    "maxlines",
    "ignore-focus",
    "border-top-right-radius",
    "cap-insets",
    "scroll-bar-auto-hide",
    "vertical-orientation",
    "skip-redirection",
    "scroll-without-focus",
    "vertical-align",
    "item-key",
    "z-index",
    "outline",
    "list-main-axis-gap",
    "sticky",
    "visibility",
    "line-height",
    "prevent-loading-on-list-scroll",
    "bounce",
    "scroll-event-throttle",
    "initial-scroll-offset",
    "outline-color",
    "outline-style",
    "bounces",
    "level",
    "blur-radius",
    "line-spacing",
    "color",
    "experimental-recycle-sticky-item",
    "column-count",
    "letter-spacing",
    "content",
    "background-repeat",
    "border-left-color",
    "mask-position",
    "background-image",
    "intersection-observers",
    "send-composing-input",
    "confirm-type",
    "text-align",
    "controls",
    "auto-size",
    "transform",
    "adjust-mode",
    "border-right-color",
    "border-right-style",
    "consume-slide-event",
    "show-soft-input-onfocus",
    "next-focus-left",
    "src",
    "placeholder",
    "background-size",
    "loop-count",
    "word-break",
    "border-top-color",
    "loop",
    "list-cross-axis-gap",
    "scroll-backward-mode",
    "next-focus-up",
    "dataset",
    "text-stroke-color",
    "hit-slop",
    "mode",
    "text-decoration",
    "next-focus-right",
    "cap-insets-scale",
    "align-focus",
    "scroll-bar-auto-hide-delay",
    "enable-font-scaling",
    "speed",
    "image-config",
    "list-container-info",
    "preload",
    "scroll-to-id",
    "image-transition-style",
    "exposure-id",
    "overflow-y",
    "scroll-bar-thumb-color",
    "white-space",
    "background-origin",
    "overflow-x",
    "background-clip",
    "scroll-bar-thumb-hover-color",
    "scroll-bar-thumb-active-color",
    "next-scrollable",
    "scroll-bar-thumb-radius",
    "initial-scroll-index",
    "allow-escape",
    "transition",
    "smart-scroll",
    "experimental-batch-render-strategy",
    "upper-threshold-item-count",
    "scroll-bar-width",
    "enable-scrollbar",
    "border-width",
    "uiappear",
    "image-rendering",
    "text-single-line-vertical-align",
    "enable-new-animator",
    "autoplay",
    "readonly",
    "auto-fix",
    "border-bottom-width",
    "animation",
    "direction",
    "transform-origin",
    "background-color",
    "placeholder-color",
    "border-top-width",
    "text-shadow",
    "uidisappear",
    "maxlength",
    "block-native-event",
    "text-maxlength",
    "text-selection",
    "filter",
    "enable-scroll",
    "animation-style",
    "user-interaction-enabled",
    "clip-path",
    "font-weight",
    "font-size",
    "font-style",
    "overflow",
    "need-visible-item-info",
    "scroll-to-index",
    "preferred-focus-child",
    "-x-auto-font-size",
    "focusable",
    "focus",
    "box-shadow",
    "enable-exposure-ui-margin",
    "background",
    "low-quality",
    "next-focus-fallback",
    "-x-auto-font-size-preset-sizes",
    "background-position",
    "use-soft-keyboard",
    "-x-app-region",
    "exposure-area",
    "border-right-width",
    "animation-velocity",
    "update-animation",
    "accessibility-element",
    "next-focus-down",
    "full-screen",
    "accessibility-elements",
    "opacity",
    "experimental-update-sticky-for-diff",
    "auto-save-last-child",
    "event-through",
    "lower-threshold-item-count",
    "font-family",
    "downsampling",
    "scroll-bar-thumb-width",
    "disabled",
    "scroll-bar-thumb-min-length",
    "accessibility-label",
    "focus-index",
    "upper-threshold",
    "placeholder-font-weight",
    "placeholder-font-size",
    "fullscreen-mode",
    "border-left-width",
    "enable-nested-scroll",
    "update-list-info",
    "text-overflow",
    "text-stroke-width",
    "focus-smooth-scroll",
    "outline-width",
    "drop-shadow",
    "defer-src-invalidation",
    "lower-threshold"};
#define StringPool ((const char *)&StringPool_contents)

static const struct TokenValue wordlist[] = {
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str38), (short)KeywordID::kType},
    {offsetof(struct StringPool_t, StringPool_str39),
     (short)KeywordID::kRepeat},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str41),
     (short)KeywordID::kScrollLeft},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str43),
     (short)KeywordID::kMaskRepeat},
    {offsetof(struct StringPool_t, StringPool_str44),
     (short)KeywordID::kMaskSize},
    {offsetof(struct StringPool_t, StringPool_str45),
     (short)KeywordID::kMaskImage},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str47),
     (short)KeywordID::kPerspective},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str51), (short)KeywordID::kTag},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str53),
     (short)KeywordID::kScrollTop},
    {offsetof(struct StringPool_t, StringPool_str54),
     (short)KeywordID::kMaskClip},
    {offsetof(struct StringPool_t, StringPool_str55),
     (short)KeywordID::kScrollEnable},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str60),
     (short)KeywordID::kScrollForwardMode},
    {offsetof(struct StringPool_t, StringPool_str61),
     (short)KeywordID::kIdselector},
    {offsetof(struct StringPool_t, StringPool_str62),
     (short)KeywordID::kScrollBarTrackColor},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str65),
     (short)KeywordID::kVisible},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str67),
     (short)KeywordID::kExposureUiMarginLeft},
    {offsetof(struct StringPool_t, StringPool_str68),
     (short)KeywordID::kExposureUiMarginRight},
    {offsetof(struct StringPool_t, StringPool_str69),
     (short)KeywordID::kItemkeys},
    {offsetof(struct StringPool_t, StringPool_str70),
     (short)KeywordID::kExposureScreenMarginLeft},
    {offsetof(struct StringPool_t, StringPool_str71),
     (short)KeywordID::kExposureScreenMarginRight},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str73),
     (short)KeywordID::kExposureUiMarginBottom},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str76),
     (short)KeywordID::kExposureScreenMarginBottom},
    {offsetof(struct StringPool_t, StringPool_str77),
     (short)KeywordID::kStickyOffset},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str79),
     (short)KeywordID::kExposureUiMarginTop},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str81),
     (short)KeywordID::kBorder},
    {offsetof(struct StringPool_t, StringPool_str82),
     (short)KeywordID::kExposureScreenMarginTop},
    {offsetof(struct StringPool_t, StringPool_str83),
     (short)KeywordID::kBottomInset},
    {offsetof(struct StringPool_t, StringPool_str84),
     (short)KeywordID::kBorderLeft},
    {offsetof(struct StringPool_t, StringPool_str85),
     (short)KeywordID::kBorderRight},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str87),
     (short)KeywordID::kBorderColor},
    {offsetof(struct StringPool_t, StringPool_str88),
     (short)KeywordID::kBorderStyle},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str90),
     (short)KeywordID::kEditOnFocus},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str96),
     (short)KeywordID::kBorderTop},
    {offsetof(struct StringPool_t, StringPool_str97),
     (short)KeywordID::kSelect},
    {offsetof(struct StringPool_t, StringPool_str98),
     (short)KeywordID::kBorderTopStyle},
    {offsetof(struct StringPool_t, StringPool_str99), (short)KeywordID::kName},
    {offsetof(struct StringPool_t, StringPool_str100),
     (short)KeywordID::kBorderBottom},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str102),
     (short)KeywordID::kMinHeight},
    {offsetof(struct StringPool_t, StringPool_str103),
     (short)KeywordID::kListType},
    {offsetof(struct StringPool_t, StringPool_str104),
     (short)KeywordID::kBorderBottomColor},
    {offsetof(struct StringPool_t, StringPool_str105),
     (short)KeywordID::kBorderBottomStyle},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str109),
     (short)KeywordID::kBorderLeftStyle},
    {offsetof(struct StringPool_t, StringPool_str110),
     (short)KeywordID::kMarkdownStyle},
    {offsetof(struct StringPool_t, StringPool_str111),
     (short)KeywordID::kPrevScrollable},
    {offsetof(struct StringPool_t, StringPool_str112),
     (short)KeywordID::kBorderRadius},
    {offsetof(struct StringPool_t, StringPool_str113),
     (short)KeywordID::kMaskOrigin},
    {offsetof(struct StringPool_t, StringPool_str114),
     (short)KeywordID::kBorderTopLeftRadius},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str116),
     (short)KeywordID::kValue},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str118),
     (short)KeywordID::kBorderBottomLeftRadius},
    {offsetof(struct StringPool_t, StringPool_str119),
     (short)KeywordID::kBorderBottomRightRadius},
    {offsetof(struct StringPool_t, StringPool_str120),
     (short)KeywordID::kCursor},
    {offsetof(struct StringPool_t, StringPool_str121), (short)KeywordID::kText},
    {offsetof(struct StringPool_t, StringPool_str122),
     (short)KeywordID::kScrollDirection},
    {offsetof(struct StringPool_t, StringPool_str123),
     (short)KeywordID::kRichtype},
    {offsetof(struct StringPool_t, StringPool_str124),
     (short)KeywordID::kScrollOrientation},
    {offsetof(struct StringPool_t, StringPool_str125),
     (short)KeywordID::kCaretColor},
    {offsetof(struct StringPool_t, StringPool_str126),
     (short)KeywordID::kScrollBarEnable},
    {offsetof(struct StringPool_t, StringPool_str127),
     (short)KeywordID::kExposureScene},
    {offsetof(struct StringPool_t, StringPool_str128),
     (short)KeywordID::kTextIndent},
    {offsetof(struct StringPool_t, StringPool_str129),
     (short)KeywordID::kNeedsVisibleCells},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str131),
     (short)KeywordID::kMaxHeight},
    {offsetof(struct StringPool_t, StringPool_str132),
     (short)KeywordID::kTextMaxline},
    {offsetof(struct StringPool_t, StringPool_str133),
     (short)KeywordID::kScrollY},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str136),
     (short)KeywordID::kTextGradient},
    {offsetof(struct StringPool_t, StringPool_str137),
     (short)KeywordID::kScrollX},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str139),
     (short)KeywordID::kMaxlines},
    {offsetof(struct StringPool_t, StringPool_str140),
     (short)KeywordID::kIgnoreFocus},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str142),
     (short)KeywordID::kBorderTopRightRadius},
    {offsetof(struct StringPool_t, StringPool_str143),
     (short)KeywordID::kCapInsets},
    {offsetof(struct StringPool_t, StringPool_str144),
     (short)KeywordID::kScrollBarAutoHide},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str146),
     (short)KeywordID::kVerticalOrientation},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str150),
     (short)KeywordID::kSkipRedirection},
    {offsetof(struct StringPool_t, StringPool_str151),
     (short)KeywordID::kScrollWithoutFocus},
    {offsetof(struct StringPool_t, StringPool_str152),
     (short)KeywordID::kVerticalAlign},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str154),
     (short)KeywordID::kItemKey},
    {offsetof(struct StringPool_t, StringPool_str155),
     (short)KeywordID::kZIndex},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str157),
     (short)KeywordID::kOutline},
    {offsetof(struct StringPool_t, StringPool_str158),
     (short)KeywordID::kListMainAxisGap},
    {offsetof(struct StringPool_t, StringPool_str159),
     (short)KeywordID::kSticky},
    {offsetof(struct StringPool_t, StringPool_str160),
     (short)KeywordID::kVisibility},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str162),
     (short)KeywordID::kLineHeight},
    {offsetof(struct StringPool_t, StringPool_str163),
     (short)KeywordID::kPreventLoadingOnListScroll},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str165),
     (short)KeywordID::kBounce},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str167),
     (short)KeywordID::kScrollEventThrottle},
    {offsetof(struct StringPool_t, StringPool_str168),
     (short)KeywordID::kInitialScrollOffset},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str170),
     (short)KeywordID::kOutlineColor},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str172),
     (short)KeywordID::kOutlineStyle},
    {offsetof(struct StringPool_t, StringPool_str173),
     (short)KeywordID::kBounces},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str176),
     (short)KeywordID::kLevel},
    {offsetof(struct StringPool_t, StringPool_str177),
     (short)KeywordID::kBlurRadius},
    {offsetof(struct StringPool_t, StringPool_str178),
     (short)KeywordID::kLineSpacing},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str180),
     (short)KeywordID::kColor},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str183),
     (short)KeywordID::kExperimentalRecycleStickyItem},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str185),
     (short)KeywordID::kColumnCount},
    {offsetof(struct StringPool_t, StringPool_str186),
     (short)KeywordID::kLetterSpacing},
    {offsetof(struct StringPool_t, StringPool_str187),
     (short)KeywordID::kContent},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str189),
     (short)KeywordID::kBackgroundRepeat},
    {offsetof(struct StringPool_t, StringPool_str190),
     (short)KeywordID::kBorderLeftColor},
    {offsetof(struct StringPool_t, StringPool_str191),
     (short)KeywordID::kMaskPosition},
    {offsetof(struct StringPool_t, StringPool_str192),
     (short)KeywordID::kBackgroundImage},
    {offsetof(struct StringPool_t, StringPool_str193),
     (short)KeywordID::kIntersectionObservers},
    {offsetof(struct StringPool_t, StringPool_str194),
     (short)KeywordID::kSendComposingInput},
    {offsetof(struct StringPool_t, StringPool_str195),
     (short)KeywordID::kConfirmType},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str197),
     (short)KeywordID::kTextAlign},
    {offsetof(struct StringPool_t, StringPool_str198),
     (short)KeywordID::kControls},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str202),
     (short)KeywordID::kAutoSize},
    {offsetof(struct StringPool_t, StringPool_str203),
     (short)KeywordID::kTransform},
    {offsetof(struct StringPool_t, StringPool_str204),
     (short)KeywordID::kAdjustMode},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str206),
     (short)KeywordID::kBorderRightColor},
    {offsetof(struct StringPool_t, StringPool_str207),
     (short)KeywordID::kBorderRightStyle},
    {offsetof(struct StringPool_t, StringPool_str208),
     (short)KeywordID::kConsumeSlideEvent},
    {offsetof(struct StringPool_t, StringPool_str209),
     (short)KeywordID::kShowSoftInputOnfocus},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str211),
     (short)KeywordID::kNextFocusLeft},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str215), (short)KeywordID::kSrc},
    {offsetof(struct StringPool_t, StringPool_str216),
     (short)KeywordID::kPlaceholder},
    {offsetof(struct StringPool_t, StringPool_str217),
     (short)KeywordID::kBackgroundSize},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str220),
     (short)KeywordID::kLoopCount},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str225),
     (short)KeywordID::kWordBreak},
    {offsetof(struct StringPool_t, StringPool_str226),
     (short)KeywordID::kBorderTopColor},
    {offsetof(struct StringPool_t, StringPool_str227), (short)KeywordID::kLoop},
    {offsetof(struct StringPool_t, StringPool_str228),
     (short)KeywordID::kListCrossAxisGap},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str231),
     (short)KeywordID::kScrollBackwardMode},
    {offsetof(struct StringPool_t, StringPool_str232),
     (short)KeywordID::kNextFocusUp},
    {offsetof(struct StringPool_t, StringPool_str233),
     (short)KeywordID::kDataset},
    {offsetof(struct StringPool_t, StringPool_str234),
     (short)KeywordID::kTextStrokeColor},
    {offsetof(struct StringPool_t, StringPool_str235),
     (short)KeywordID::kHitSlop},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str237), (short)KeywordID::kMode},
    {offsetof(struct StringPool_t, StringPool_str238),
     (short)KeywordID::kTextDecoration},
    {offsetof(struct StringPool_t, StringPool_str239),
     (short)KeywordID::kNextFocusRight},
    {offsetof(struct StringPool_t, StringPool_str240),
     (short)KeywordID::kCapInsetsScale},
    {offsetof(struct StringPool_t, StringPool_str241),
     (short)KeywordID::kAlignFocus},
    {offsetof(struct StringPool_t, StringPool_str242),
     (short)KeywordID::kScrollBarAutoHideDelay},
    {offsetof(struct StringPool_t, StringPool_str243),
     (short)KeywordID::kEnableFontScaling},
    {offsetof(struct StringPool_t, StringPool_str244),
     (short)KeywordID::kSpeed},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str247),
     (short)KeywordID::kImageConfig},
    {offsetof(struct StringPool_t, StringPool_str248),
     (short)KeywordID::kListContainerInfo},
    {offsetof(struct StringPool_t, StringPool_str249),
     (short)KeywordID::kPreload},
    {offsetof(struct StringPool_t, StringPool_str250),
     (short)KeywordID::kScrollToId},
    {offsetof(struct StringPool_t, StringPool_str251),
     (short)KeywordID::kImageTransitionStyle},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str253),
     (short)KeywordID::kExposureId},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str255),
     (short)KeywordID::kOverflowY},
    {offsetof(struct StringPool_t, StringPool_str256),
     (short)KeywordID::kScrollBarThumbColor},
    {offsetof(struct StringPool_t, StringPool_str257),
     (short)KeywordID::kWhiteSpace},
    {offsetof(struct StringPool_t, StringPool_str258),
     (short)KeywordID::kBackgroundOrigin},
    {offsetof(struct StringPool_t, StringPool_str259),
     (short)KeywordID::kOverflowX},
    {offsetof(struct StringPool_t, StringPool_str260),
     (short)KeywordID::kBackgroundClip},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str262),
     (short)KeywordID::kScrollBarThumbHoverColor},
    {offsetof(struct StringPool_t, StringPool_str263),
     (short)KeywordID::kScrollBarThumbActiveColor},
    {offsetof(struct StringPool_t, StringPool_str264),
     (short)KeywordID::kNextScrollable},
    {offsetof(struct StringPool_t, StringPool_str265),
     (short)KeywordID::kScrollBarThumbRadius},
    {offsetof(struct StringPool_t, StringPool_str266),
     (short)KeywordID::kInitialScrollIndex},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str268),
     (short)KeywordID::kAllowEscape},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str270),
     (short)KeywordID::kTransition},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str275),
     (short)KeywordID::kSmartScroll},
    {offsetof(struct StringPool_t, StringPool_str276),
     (short)KeywordID::kExperimentalBatchRenderStrategy},
    {offsetof(struct StringPool_t, StringPool_str277),
     (short)KeywordID::kUpperThresholdItemCount},
    {offsetof(struct StringPool_t, StringPool_str278),
     (short)KeywordID::kScrollBarWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str280),
     (short)KeywordID::kEnableScrollbar},
    {offsetof(struct StringPool_t, StringPool_str281),
     (short)KeywordID::kBorderWidth},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str285),
     (short)KeywordID::kUiappear},
    {offsetof(struct StringPool_t, StringPool_str286),
     (short)KeywordID::kImageRendering},
    {offsetof(struct StringPool_t, StringPool_str287),
     (short)KeywordID::kTextSingleLineVerticalAlign},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str290),
     (short)KeywordID::kEnableNewAnimator},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str293),
     (short)KeywordID::kAutoplay},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str295),
     (short)KeywordID::kReadonly},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str297),
     (short)KeywordID::kAutoFix},
    {offsetof(struct StringPool_t, StringPool_str298),
     (short)KeywordID::kBorderBottomWidth},
    {offsetof(struct StringPool_t, StringPool_str299),
     (short)KeywordID::kAnimation},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str307),
     (short)KeywordID::kDirection},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str312),
     (short)KeywordID::kTransformOrigin},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str316),
     (short)KeywordID::kBackgroundColor},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str320),
     (short)KeywordID::kPlaceholderColor},
    {offsetof(struct StringPool_t, StringPool_str321),
     (short)KeywordID::kBorderTopWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str323),
     (short)KeywordID::kTextShadow},
    {offsetof(struct StringPool_t, StringPool_str324),
     (short)KeywordID::kUidisappear},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str326),
     (short)KeywordID::kMaxlength},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str331),
     (short)KeywordID::kBlockNativeEvent},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str333),
     (short)KeywordID::kTextMaxlength},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str336),
     (short)KeywordID::kTextSelection},
    {offsetof(struct StringPool_t, StringPool_str337),
     (short)KeywordID::kFilter},
    {offsetof(struct StringPool_t, StringPool_str338),
     (short)KeywordID::kEnableScroll},
    {offsetof(struct StringPool_t, StringPool_str339),
     (short)KeywordID::kAnimationStyle},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str344),
     (short)KeywordID::kUserInteractionEnabled},
    {offsetof(struct StringPool_t, StringPool_str345),
     (short)KeywordID::kClipPath},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str347),
     (short)KeywordID::kFontWeight},
    {offsetof(struct StringPool_t, StringPool_str348),
     (short)KeywordID::kFontSize},
    {offsetof(struct StringPool_t, StringPool_str349),
     (short)KeywordID::kFontStyle},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str353),
     (short)KeywordID::kOverflow},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str355),
     (short)KeywordID::kNeedVisibleItemInfo},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str358),
     (short)KeywordID::kScrollToIndex},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str361),
     (short)KeywordID::kPreferredFocusChild},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str365),
     (short)KeywordID::kXAutoFontSize},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str370),
     (short)KeywordID::kFocusable},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str373),
     (short)KeywordID::kFocus},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str375),
     (short)KeywordID::kBoxShadow},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str379),
     (short)KeywordID::kEnableExposureUiMargin},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str381),
     (short)KeywordID::kBackground},
    {offsetof(struct StringPool_t, StringPool_str382),
     (short)KeywordID::kLowQuality},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str384),
     (short)KeywordID::kNextFocusFallback},
    {offsetof(struct StringPool_t, StringPool_str385),
     (short)KeywordID::kXAutoFontSizePresetSizes},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str387),
     (short)KeywordID::kBackgroundPosition},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str390),
     (short)KeywordID::kUseSoftKeyboard},
    {offsetof(struct StringPool_t, StringPool_str391),
     (short)KeywordID::kXAppRegion},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str397),
     (short)KeywordID::kExposureArea},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str400),
     (short)KeywordID::kBorderRightWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str402),
     (short)KeywordID::kAnimationVelocity},
    {offsetof(struct StringPool_t, StringPool_str403),
     (short)KeywordID::kUpdateAnimation},
    {offsetof(struct StringPool_t, StringPool_str404),
     (short)KeywordID::kAccessibilityElement},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str407),
     (short)KeywordID::kNextFocusDown},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str410),
     (short)KeywordID::kFullScreen},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str415),
     (short)KeywordID::kAccessibilityElements},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str421),
     (short)KeywordID::kOpacity},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str430),
     (short)KeywordID::kExperimentalUpdateStickyForDiff},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str434),
     (short)KeywordID::kAutoSaveLastChild},
    {offsetof(struct StringPool_t, StringPool_str435),
     (short)KeywordID::kEventThrough},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str437),
     (short)KeywordID::kLowerThresholdItemCount},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str442),
     (short)KeywordID::kFontFamily},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str448),
     (short)KeywordID::kDownsampling},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str450),
     (short)KeywordID::kScrollBarThumbWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str452),
     (short)KeywordID::kDisabled},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str455),
     (short)KeywordID::kScrollBarThumbMinLength},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str465),
     (short)KeywordID::kAccessibilityLabel},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str468),
     (short)KeywordID::kFocusIndex},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str474),
     (short)KeywordID::kUpperThreshold},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str480),
     (short)KeywordID::kPlaceholderFontWeight},
    {offsetof(struct StringPool_t, StringPool_str481),
     (short)KeywordID::kPlaceholderFontSize},
    {offsetof(struct StringPool_t, StringPool_str482),
     (short)KeywordID::kFullscreenMode},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str487),
     (short)KeywordID::kBorderLeftWidth},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str490),
     (short)KeywordID::kEnableNestedScroll},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str492),
     (short)KeywordID::kUpdateListInfo},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str526),
     (short)KeywordID::kTextOverflow},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str531),
     (short)KeywordID::kTextStrokeWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str553),
     (short)KeywordID::kFocusSmoothScroll},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str558),
     (short)KeywordID::kOutlineWidth},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str561),
     (short)KeywordID::kDropShadow},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str599),
     (short)KeywordID::kDeferSrcInvalidation},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str634),
     (short)KeywordID::kLowerThreshold}};

const struct TokenValue *KeywordHash::find(const char *str, unsigned int len) {
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH) {
    unsigned int key = hash(str, len);

    if (key <= MAX_HASH_VALUE) {
      int o = wordlist[key].name;
      if (o >= 0) {
        const char *s = o + StringPool;

        if (*str == *s && !strcmp(str + 1, s + 1)) return &wordlist[key];
      }
    }
  }
  return 0;
}

static_assert(sizeof(StringPool_contents) < 32767);

KeywordID GetKeywordID(const std::string &str) {
  auto *tk = KeywordHash::find(str.c_str(), str.size());
  return tk ? static_cast<KeywordID>(tk->id) : KeywordID::kInvalid;
}

}  // namespace clay
